### ISSUE TITLE
Binary to Text

### ISSUE THREAD

**Issue by smileali9** [codewithpom/binary-html#1]
Text to Binary is working fine 
But Binary to Text not working please check the attachment 

<img width="622" alt="binary-to-text" src="https://user-images.githubusercontent.com/57975829/189534760-aeb5c07a-a562-44b3-9e7c-bf3077f49092.png">
<img width="577" alt="text-to-binary" src="https://user-images.githubusercontent.com/57975829/189534762-2596e6c4-3b88-4603-98e2-d66be8a202ae.png">

**Comment by codewithpom** [comment]
Thanks for reporting will be fixed soon
